// <auto-generated />
using System;
using FleetControlRH.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetControlRH.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613120000_AddAbastecimentoCombustiveis")]
    partial class AddAbastecimentoCombustiveis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetControlRH.Api.Models.Abastecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataAbastecimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("FotoNotaFiscal")
                        .HasColumnType("bytea");

                    b.Property<string>("FotoNotaFiscalContentType")
                        .HasColumnType("text");

                    b.Property<string>("FotoNotaFiscalPath")
                        .HasColumnType("text");

                    b.Property<int>("KmAtual")
                        .HasColumnType("integer");

                    b.Property<decimal>("Litros")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Posto")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("MotoristaId", "DataAbastecimento");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("VeiculoId", "DataAbastecimento");

                    b.ToTable("Abastecimentos");
                });

            modelBuilder.Entity("FleetControlRH.Api.Models.AbastecimentoCombustivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbastecimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("DescricaoCombustivel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Litros")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("AbastecimentoId");

                    b.ToTable("AbastecimentoCombustiveis");
                });

            modelBuilder.Entity("FleetControlRH.Api.Models.AbastecimentoCombustivel", b =>
                {
                    b.HasOne("FleetControlRH.Api.Models.Abastecimento", "Abastecimento")
                        .WithMany("Combustiveis")
                        .HasForeignKey("AbastecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abastecimento");
                });
#pragma warning restore 612, 618
        }
    }
}
